#!/bin/sh
set -eux

# Add sociomantic-tsunami mxnet APT repo
dist="$(lsb_release -cs)"
echo "deb https://dl.bintray.com/sociomantic-tsunami/mxnet $dist release prerelease" \
    >> /etc/apt/sources.list.d/mxnet.list

# Update already-installed packages
apt-get update
apt-get -y upgrade

# Install dmxnet dependencies
apt-get install -y \
    libmxnet=1.2.0-0tsunami1+rc.1~xenial \
    zlib1g-dev
